

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.

include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - parameter_assignments
    - require_trailing_commas

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  # This shouldn't be excluded but the types on parsers are very hard
  exclude:
    - "**/*_parser.dart"
    